name: CI

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Deploy is handled by Render using Dockerfile
  # just run list and tests for fun
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Run Prettier
        run: yarn format:check
      - name: Test
        run: yarn test
